# Generated by Django 5.0.4 on 2024-04-26 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisings", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={
                "ordering": ["pk"],
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
            },
        ),
        migrations.AddField(
            model_name="collect",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор сбора",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collect",
            name="collected",
            field=models.IntegerField(default=0, verbose_name="Собрано"),
        ),
        migrations.AddField(
            model_name="collect",
            name="collected_on",
            field=models.DateTimeField(
                default=None, verbose_name="Дата завершения сбора"
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="collect",
            name="image",
            field=models.ImageField(
                null=True, upload_to="donated/image", verbose_name="Картинка сбора"
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="payments",
            field=models.ManyToManyField(
                related_name="collection", to="payments.payment", verbose_name="Донаты"
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="reason",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Повод сбора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collect",
            name="title",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Название сбора"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collect",
            name="to_collect",
            field=models.IntegerField(default=1, verbose_name="Сумма сбора"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collect",
            name="users_donated",
            field=models.IntegerField(default=0, verbose_name="Задонатило"),
        ),
    ]
