# Generated by Django 5.0.4 on 2024-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisings", "0002_alter_collect_options_collect_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="image",
            field=models.ImageField(
                null=True, upload_to="collections/image", verbose_name="Картинка сбора"
            ),
        ),
    ]
