# Generated by Django 5.0.4 on 2024-04-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisings", "0003_alter_collect_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collect",
            name="payments",
        ),
    ]
