# Generated by Django 5.0.4 on 2024-04-26 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Сумма доната")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата отправления"
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(default=False, verbose_name="Показывать сумму"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Донат",
                "verbose_name_plural": "Донаты",
                "ordering": ["date"],
            },
        ),
    ]
