# Generated by Django 5.0.4 on 2024-04-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisings", "0004_remove_collect_payments"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="donations",
                to="fundraisings.collect",
                verbose_name="Отправлено на",
            ),
            preserve_default=False,
        ),
    ]
